const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const titles={workbench:'Agentic Workbench',agents:'Industrial Agents',knowledge:'Knowledge Vault',engineering:'Engineering Intelligence',artifacts:'Artifact Studio',security:'Sovereignty & Security',audit:'Audit Ledger',admin:'Models & Administration'};
const recent=[['⛨','Inspection report → Approval note','8 steps • Vision + Reasoning • 3 citations','2 min ago'],['⌘','Pump efficiency calculator','11 steps • Code model • Sandbox verified','18 min ago'],['▤','Vendor proposal comparison','7 steps • Reasoning • 4 source documents','42 min ago']];
const agents=[['⛨','Inspection Review Agent','Reads scanned reports, retrieves SOPs, scores deviations and generates approval notes.','Vision + RAG','8 tools'],['⌘','Secure Coding Agent','Plans, writes, executes, tests and repairs code inside a network-isolated sandbox.','Coder','7 tools'],['⌬','P&ID Intelligence Agent','Extracts equipment, symbols, tags and connectivity from engineering drawings.','Vision','5 tools'],['▧','Executive Artifact Agent','Transforms verified findings into Word, Excel, PDF and PowerPoint deliverables.','Reasoner','6 tools']];
const artifacts=[['DOCX','MRPL_Approval_Note.docx','Verified approval note with findings, citations and recommended actions.','428 KB'],['XLSX','Pump_Efficiency_Analysis.xlsx','Calculated efficiency table with formulas and embedded performance chart.','276 KB'],['PPTX','Inspection_Management_Brief.pptx','8-slide management brief generated from validated inspection findings.','1.8 MB'],['PY','pump_analysis.py','Sandbox-tested Python utility with local unit tests and no network access.','18 KB']];
const audits=[['02:33:48','Artifact verified','Inspection Agent','MRPL_Approval_Note.docx','PASS'],['02:33:45','Local model inference','Model Router','raksha-reasoner','PASS'],['02:33:39','Knowledge retrieval','RAG Engine','SOP-MECH-017 §6.2','PASS'],['02:33:30','OCR + vision extraction','Inspection Agent','inspection_report.pdf','PASS'],['02:31:14','Network policy check','Security Daemon','Outbound egress','0 B'],['02:27:08','Sandbox destroyed','Coding Agent','sandbox_8FD2','PASS']];
$('#recentRuns').innerHTML=recent.map(x=>`<div class="runitem"><div class="ri">${x[0]}</div><div><b>${x[1]}</b><small>${x[2]}</small></div><span>${x[3]}</span></div>`).join('');
$('#agentGrid').innerHTML=agents.map((x,i)=>`<div class="agent-card"><div class="agenticon">${x[0]}</div><h3>${x[1]}</h3><p>${x[2]}</p><div class="agentmeta"><span>${x[3]}</span><span>${x[4]}</span></div></div>`).join('');
$('#artifactGrid').innerHTML=artifacts.map(x=>`<div class="artifact-card"><div class="filetype">${x[0]}</div><h3>${x[1]}</h3><p>${x[2]}</p><div class="artifact-foot"><span>✓ VERIFIED</span><span>${x[3]}</span></div></div>`).join('');
$('#auditRows').innerHTML=audits.map(x=>`<tr><td>${x[0]}</td><td><b>${x[1]}</b></td><td>${x[2]}</td><td>${x[3]}</td><td><span class="ready">● ${x[4]}</span></td></tr>`).join('');
$$('.nav').forEach(b=>b.onclick=()=>{ $$('.nav').forEach(x=>x.classList.remove('active')); b.classList.add('active'); $$('.view').forEach(x=>x.classList.remove('active')); $('#view-'+b.dataset.view).classList.add('active'); $('#pageTitle').textContent=titles[b.dataset.view]; window.scrollTo({top:0,behavior:'smooth'}) });
$$('.suggestions button').forEach(b=>b.onclick=()=>{$('#prompt').value=b.dataset.prompt});
const workflows={inspection:{title:'Industrial Inspection Agent',model:'Vision/OCR → Reasoning selected',reason:'Scanned PDF + SOP comparison + deliverable generation',steps:[['Classify input','Detected scanned inspection report + SOP','0.2s'],['Extract text & visual findings','PaddleOCR + local vision model','2.1s'],['Identify equipment & observations','12 observations • 4 equipment tags','1.4s'],['Retrieve applicable SOP sections','Hybrid search + reranker • 6 passages','0.8s'],['Cross-check deviations','3 critical • 2 medium • 7 compliant','1.8s'],['Run deterministic risk calculation','Python tool • verified','0.3s'],['Generate approval note','DOCX renderer • citations embedded','1.1s'],['Validate artifact','Schema + file integrity + provenance','0.4s']],result:['Approval note ready','3 critical deviations found and cross-verified against SOP-MECH-017.']},code:{title:'Secure Coding Agent',model:'Code model selected',reason:'Software development + execution + verification detected',steps:[['Parse coding objective','Pump efficiency calculator from CSV','0.1s'],['Design implementation plan','Parser → calculator → chart → tests','0.5s'],['Generate Python source','Local coder model','1.5s'],['Create isolated sandbox','Docker • --network none','0.4s'],['Execute test suite','1 failure detected','0.7s'],['Repair implementation','Division-by-zero edge case fixed','0.8s'],['Re-run tests','12/12 tests passing','0.6s'],['Generate verified artifacts','PY + XLSX + PNG','0.9s']],result:['Code verified','12/12 tests pass inside an ephemeral network-isolated sandbox.']},pid:{title:'P&ID Intelligence Agent',model:'Vision model selected',reason:'Engineering drawing + topology extraction detected',steps:[['Tile high-resolution drawing','12 overlapping tiles','0.5s'],['Run OCR','17 tags extracted','1.4s'],['Detect symbols','Pump, vessel, valve, indicators','1.6s'],['Build topology graph','26 nodes • 31 edges','0.9s'],['Resolve target P-101','4 direct/branch connections','0.4s'],['Vision-language verification','Cross-check graph against drawing','1.2s']],result:['Topology extracted','P-101 traced to V-12, PI-104, FT-105 and XV-101 with provenance.']}};
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
async function runFlow(kind='inspection'){
 const w=workflows[kind]; $('#modalTitle').textContent=w.title;$('#routeModel').textContent=w.model;$('#routeReason').textContent=w.reason;$('#resultTitle').textContent='Processing…';$('#resultText').textContent='Local agent is executing the verified workflow.';$('#runModal').classList.add('show');$('#steps').innerHTML=w.steps.map((s,i)=>`<div class="exec-step" data-i="${i}"><div class="stepstate">${i+1}</div><div><b>${s[0]}</b><small>${s[1]}</small></div><span>${s[2]}</span></div>`).join('');
 for(let i=0;i<w.steps.length;i++){const st=$(`.exec-step[data-i="${i}"]`);st.classList.add('running');await new Promise(r=>setTimeout(r,340));st.classList.remove('running');st.classList.add('done');$('.stepstate',st).textContent='✓';}
 $('#resultTitle').textContent=w.result[0];$('#resultText').textContent=w.result[1];renderTrace(w);toast('Workflow completed locally • external calls: 0');
}
function renderTrace(w){$('#trace').innerHTML=w.steps.map((s,i)=>`<div class="trace-step"><div class="num">✓</div><b>${s[0]}</b><small>${s[1]}</small><span>${s[2]}</span></div>`).join('')}
$('#runAgent').onclick=()=>{const p=$('#prompt').value.toLowerCase();runFlow(p.includes('python')||p.includes('code')?'code':p.includes('p&id')||p.includes('p-101')?'pid':'inspection')};
$('#analyzePid').onclick=()=>{$('#pidHighlight').classList.add('active');runFlow('pid')};
$('#closeModal').onclick=()=>$('#runModal').classList.remove('show');
$('#runModal').onclick=e=>{if(e.target.id==='runModal')$('#runModal').classList.remove('show')};
$('#artifactButton').onclick=()=>toast('Artifact passed validation and is ready for local export');
$('#newTask').onclick=()=>{$$('.nav')[0].click();$('#prompt').focus();toast('New sovereign task ready')};
